### ISSUE TITLE
Functions to encode/decode secret

### ISSUE THREAD

**Issue by Kearsan** [AlexXanderGrib/otp#1]
Hello @AlexXanderGrib 

I came across your project and I have to say that it deserves far more love and consideration. Most of otp projects are unmaintained or bad designed, when yours is fast, efficient and clean. I'll start to use it soon in a production app.

If I open this post, apart from congratulating you, is that I would like to see functions to encode/decode the secret generated from generateKey.

Currently the process is pretty simple, we generate a key with generateKey, create the totp URL with getKeyUri (and in this process I believe that you convert the Uint8Array bytes from generateKey to the string secret we can see in the built URL).

For now I JSON.stringify the result of generateKey to get a storable secret to keep it linked to the user, and then I reconstruct the Uint8Array from an iterable function when I need it, it works pretty well but I find it ugly. I'd like to be able to go from the bytes generated by generateKey to the string secret in the totp URL and back to the Uint8Array.

It would be cleaner I think to store the secret as it is in the URL and then be able to challenge the code given by the user from this string secret.

Again congratulations for this project, I wish you the best !

Regards,

**Comment by AlexXanderGrib** [comment]
Hello, there is exported functions just for making key transferable:

```typescript
function importKey(base32text: string): SecretKey
function exportKey(key: SecretKey): string
```

Hope this helps

**Comment by Kearsan** [comment]
Thank you, I didn't know of these functions! It surely helps.
